# Generated by Django 2.2.10 on 2020-05-24 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mp2_api', '0002_auto_20200523_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='id',
        ),
        migrations.AddField(
            model_name='client',
            name='drone_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mp2_api.Drone'),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='drone',
            name='drone_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
