# Generated by Django 2.2.10 on 2020-05-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp2_api', '0003_auto_20200524_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='logout_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='drone',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='drone',
            name='log',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='drone',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='drone',
            name='users_connected',
            field=models.IntegerField(default=0),
        ),
    ]
