# Generated by Django 2.2.10 on 2020-05-30 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mp2_api', '0004_auto_20200529_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drone',
            old_name='status',
            new_name='state',
        ),
    ]
