# Generated by Django 2.2.10 on 2020-05-31 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mp2_api', '0005_auto_20200530_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='drone_id',
        ),
    ]
