# Generated by Django 2.2.10 on 2020-05-31 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mp2_api', '0006_remove_client_drone_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='drone_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mp2_api.Drone'),
        ),
    ]
