# Generated by Django 2.2.10 on 2020-05-31 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mp2_api', '0007_client_drone_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='drone_id',
            new_name='drone',
        ),
    ]
